"""empty message

Revision ID: 60b3666c227e
Revises: c6d8e6a51773
Create Date: 2024-08-20 00:30:52.475218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3666c227e'
down_revision = 'c6d8e6a51773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_author', sa.Boolean(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    with op.batch_alter_table('role', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_role_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_name'), ['name'], unique=False)

    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('JSONB', sa.JSONB(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='world'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity', schema='world')
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_name'))

    op.drop_table('users', schema='auth')
    with op.batch_alter_table('role', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_role_name'))

    op.drop_table('role', schema='auth')
    # ### end Alembic commands ###
