"""empty message

Revision ID: e0eb4044a223
Revises: 9e7fea37616c
Create Date: 2024-08-20 10:15:41.385806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0eb4044a223'
down_revision = '9e7fea37616c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_author', sa.Boolean(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    with op.batch_alter_table('role', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_role_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_users_name'), ['name'], unique=False)

    op.create_table('entity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='world'
    )
    op.execute("INSERT INTO auth.role VALUES ('69860c71-5262-41dc-9b7c-913d3e6a99f9','guest',false,false,false,true)")
    op.execute("INSERT INTO auth.role VALUES ('69860c71-5262-41dc-9b7c-913d3e6a9910','admin',true,false,false,true)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity', schema='world')
    with op.batch_alter_table('users', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_users_name'))

    op.drop_table('users', schema='auth')
    with op.batch_alter_table('role', schema='auth') as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_role_name'))

    op.drop_table('role', schema='auth')
    # ### end Alembic commands ###
